# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.8 and later.
- python=3.8.16

- pip:
  - azureml-train-automl-runtime==1.49.0
  - inference-schema
  - azureml-interpret==1.49.0
  - azureml-defaults==1.49.0
  - pytorch-transformers==1.0.0
  - spacy==2.1.8
  - https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
- numpy==1.22.3
- pandas==1.1.5
- scikit-learn==0.22.1
- py-xgboost<=1.3.3
- fbprophet==0.7.1
- holidays==0.10.3
- psutil==5.9.0
- pytorch==1.7.1
- cudatoolkit==11.0.221
channels:
- anaconda
- conda-forge
- pytorch
